cord:
  admin:
    password: ${CORD_ADMIN_PASSWORD}
  init:
    load-language-data: false
cord-api:
  url: ${CORD_API_GRAPHQL_URL}
  email: ${CORD_API_EMAIL}
  password: ${CORD_API_PASSWORD}
server:
  port: ${SERVER_PORT}
  url: ${SERVER_URL}
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_DATABASE}
    driverClassName: software.aws.rds.jdbc.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ssl: false
  hikari:
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    maximum-pool-size: 10 #maximum pool size
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
    auto-commit: true #default auto-commit behavior.
springdoc:
  swagger-ui:
    servers:
      - url: ${SWAGGER_URL}
    path: /swagger-ui/index.html
    schemes: [https]
    disable-swagger-default-url: true
