package com.seedcompany.cordtables.components.tables.sc.projects

data class project(
    var id: String? = null,

    val neo4j_id: String? = null,
    val name: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val department: String? = null,
    val estimated_submission: String? = null,
    val field_region: String? = null,
    val initial_mou_end: String? = null,
    val marketing_location: String? = null,
    val mou_start: String? = null,
    val mou_end: String? = null,
    val owning_organization: String? = null,
    val periodic_reports_directory: String? = null,
    val posts_directory: String? = null,
    val primary_location: String? = null,
    val root_directory: String? = null,
    val status: String? = null,
    val status_changed_at: String? = null,
    val step: String? = null,

    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

data class projectInput(
    var id: String? = null,
    val neo4j_id: String? = null,
    val name: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val department: String? = null,
    val estimated_submission: String? = null,
    val field_region: String? = null,
    val initial_mou_end: String? = null,
    val marketing_location: String? = null,
    val mou_start: String? = null,
    val mou_end: String? = null,
    val owning_organization: String? = null,
    val periodic_reports_directory: String? = null,
    val posts_directory: String? = null,
    val primary_location: String? = null,
    val root_directory: String? = null,
    val status: String? = null,
    val status_changed_at: String? = null,
    val step: String? = null,
    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)
