package com.seedcompany.cordtables.components.tables.sil.table_of_languages_in_country

data class tableOfLanguagesInCountry(
    var id: String? = null,

    val iso_639: String? = null,
    val language_name: String? = null,
    val uninverted_name: String? = null,
    val country_code: String? = null,
    val country_name: String? = null,
    val region_code: String? = null,
    val region_name: String? = null,
    val area: String? = null,
    val is_primary: String? = null,
    val is_indigenous: String? = null,
    val is_established: String? = null,
    val all_users: Int? = null,
    val l1_users: Int? = null,
    val l2_users: Int? = null,
    val family: String? = null,
    val egids: String? = null,
    val function_code: String? = null,
    val function_label: String? = null,
    val institutional: Int? = null,
    val developing: Int? = null,
    val vigorous: Int? = null,
    val in_trouble: Int? = null,
    val dying: Int? = null,
    val extinct: Int? = null,

    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

data class tableOfLanguagesInCountryInput(
    var id: String? = null,
    val iso_639: String? = null,
    val language_name: String? = null,
    val uninverted_name: String? = null,
    val country_code: String? = null,
    val country_name: String? = null,
    val region_code: String? = null,
    val region_name: String? = null,
    val area: String? = null,
    val is_primary: String? = null,
    val is_indigenous: String? = null,
    val is_established: String? = null,
    val all_users: Int? = null,
    val l1_users: Int? = null,
    val l2_users: Int? = null,
    val family: String? = null,
    val egids: String? = null,
    val function_code: String? = null,
    val function_label: String? = null,
    val institutional: Int? = null,
    val developing: Int? = null,
    val vigorous: Int? = null,
    val in_trouble: Int? = null,
    val dying: Int? = null,
    val extinct: Int? = null,
    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

