#org:
#  neo4j:
#    driver:
#      uri: ${NEO4J_URL}
#      authentication:
#        username: ${NEO4J_USERNAME}
#        password: ${NEO4J_PASSWORD}
cord:
  admin:
    password: ${CORD_ADMIN_PASSWORD}
  init:
    load-language-data: false
  awsAccessKeyId: "AKIASBJ5CYUYBNWLM2XC" # ${AWS_ACCESS_KEY_ID}
  awsSecretAccessKey: "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" #${AWS_SECRET_ACCESS_KEY}
  email:
    server: "http://localhost:3333" #${EMAIL_SERVER}
cord-api:
  url: ${CORD_API_GRAPHQL_URL}
  email: ${CORD_API_EMAIL}
  password: ${CORD_API_PASSWORD}
server:
  port: ${SERVER_PORT}
  url: ${SERVER_URL}
spring:
  mvc:
    async:
      request-timeout: -1
  datasource:
    jdbcUrl: jdbc:postgresql://${DB_DOMAIN}:${DB_PORT}/${DB_DATABASE}
    driverClassName: software.aws.rds.jdbc.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ssl: false
  hikari:
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    maximum-pool-size: 10 #maximum pool size
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
    auto-commit: true #default auto-commit behavior.
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
