package com.seedcompany.cordtables.components.tables.common.cell_channels

data class CellChannel(
        val id: String? = null,
        val table_name: String? = null,
        val column_name: String? = null,
        val row: Int? = null,
        val created_at: String? = null,
        val created_by: Int? = null,
        val modified_at: String? = null,
        val modified_by: Int? = null,
        val owning_person: Int? = null,
        val owning_group: Int? = null,
)

data class CellChannelInput(
        val table_name: String,
        val column_name: String,
        val row: Int,
)


enum class TableName {
//    `admin.database_version_control`
//    `admin.database_version_control`,
//    `admin.email_tokens`,
//    `admin.group_memberships`,
//    `admin.group_row_access`,
//    `admin.groups`,
//    `admin.peers`,
//    `admin.people`,
//    `admin.role_column_grants`,
//    `admin.role_memberships`,
//    `admin.role_table_permissions`,
//    `admin.roles`,
//    `admin.tokens`,
//    `admin.users`,
//    `common.blogs`,
//    `common.blog_posts`,
//    `common.cell_channels`,
//    `common.directories`,
//    `common.discussion_channels`,
//    `common.education_by_person`,
//    `common.education_entries`,
//    `common.file_versions`,
//    `common.files`,
//    `common.locations`,
//    `common.organizations`,
//    `common.people_to_org_relationships`,
//    `common.posts`,
//    `common.scripture_references`,
//    `common.site_text`,
//    `common.stage_graph`,
//    `common.stage_notifications`,
//    `common.stage_role_column_grantscommon.stages`,
//    `common.threads`,
//    `common.ticket_assignments`,
//    `common.ticket_feedback`,
//    `common.ticket_graph`,
//    `common.tickets`,
//    `common.work_estimates`,
//    `common.work_records`,
//    `common.workflows`,
//    `sil.country_codes`,
//    `sil.language_codes`,
//    `sil.language_index`,
//    `sc.ethnologue`,
//    `sc.budget_records`,
//    `sc.budgets`,
//    `sc.ceremoniessc.change_to_plans`,
//    `sc.field_regions`,
//    `sc.field_zones`,
//    `sc.funding_accounts`,
//    `sc.internship_engagements`,
//    `sc.known_languages_by_person`,
//    `sc.language_engagements`,
//    `sc.languages`,
//    `sc.locations`,
//    `sc.organization_locations`,
//    `sc.organizations`,
//    `sc.partners`,
//    `sc.partnerships`,
//    `sc.people`,
//    `sc.person_unavailabilities`,
//    `sc.pinned_projects`,
//    `sc.posts`,
//    `sc.product_scripture_references`,
//    `sc.products`,
//    `sc.project_locations`,
//    `sc.project_members`,
//    `sc.projects`,
//    `sc.language_goal_definitions`,
//    `sc.language_locations`,
//    `sc.language_goals`,
//    `sc.periodic_reports`
}

