package com.seedcompany.cordtables.components.tables.sc.language_engagements

data class languageEngagement(
    var id: String? = null,
    val neo4j_id: String? = null,
    val project: Int? = null,
    val ethnologue: Int? = null,
    val change_to_plan: Int? = null,
    val active: Boolean? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val initial_end_date: String? = null,
    val is_first_scripture: Boolean? = null,
    val is_luke_partnership: Boolean? = null,
    val is_sent_printing: Boolean? = null,
    val last_reactivated_at: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: Int? = null,
    val pnp: String? = null,
    val pnp_file: Int? = null,
    val product_engagement_tag: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val created_at: String? = null,
    val created_by: Int? = null,
    val modified_at: String? = null,
    val modified_by: Int? = null,
    val owning_person: Int? = null,
    val owning_group: Int? = null,
)

data class languageEngagementInput(
    var id: String? = null,
    val neo4j_id: String? = null,
    val project: Int? = null,
    val ethnologue: Int? = null,
    val change_to_plan: Int? = null,
    val active: Boolean? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val initial_end_date: String? = null,
    val is_first_scripture: Boolean? = null,
    val is_luke_partnership: Boolean? = null,
    val is_sent_printing: Boolean? = null,
    val last_reactivated_at: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: Int? = null,
    val pnp: String? = null,
    val pnp_file: Int? = null,
    val product_engagement_tag: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val created_at: String? = null,
    val created_by: Int? = null,
    val modified_at: String? = null,
    val modified_by: Int? = null,
    val owning_person: Int? = null,
    val owning_group: Int? = null,
)
