package com.seedcompany.cordtables.components.tables.sc.language_engagements

data class languageEngagement(
    var id: String? = null,

    val project: String? = null,
    val ethnologue: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val ceremony: String? = null,
    val is_open_to_investor_visit: Boolean? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val initial_end_date: String? = null,
    val is_first_scripture: Boolean? = null,
    val is_luke_partnership: Boolean? = null,
    val is_sent_printing: Boolean? = null,
    val last_suspended_at: String? = null,
    val last_reactivated_at: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: String? = null,
    val pnp: String? = null,
    val pnp_file: String? = null,
    val product_engagement_tag: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val status_modified_at: String? = null,
    val historic_goal: String? = null,
    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

data class languageEngagementInput(
    var id: String? = null,

    val project: String? = null,
    val ethnologue: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val ceremony: String? = null,
    val is_open_to_investor_visit: Boolean? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val initial_end_date: String? = null,
    val is_first_scripture: Boolean? = null,
    val is_luke_partnership: Boolean? = null,
    val is_sent_printing: Boolean? = null,
    val last_suspended_at: String? = null,
    val last_reactivated_at: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: String? = null,
    val pnp: String? = null,
    val pnp_file: String? = null,
    val product_engagement_tag: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val status_modified_at: String? = null,
    val historic_goal: String? = null,
    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)
