package com.seedcompany.cordtables.components.tables.sc.internship_engagements

data class internshipEngagement(
    var id: String? = null,

    val project: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val ceremony: String? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val country_of_origin: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val growth_plan: String? = null,
    val initial_end_date: String? = null,
    val intern: String? = null,
    val last_reactivated_at: String? = null,
    val mentor: String? = null,
    val methodologies: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: String? = null,
    val position: String? = null,
    val sensitivity: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val status_modified_at: String? = null,
    val last_suspended_at: String? = null,

    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

//project uuid references sc.projects(id), -- not null
//change_to_plan uuid references sc.change_to_plans(id), -- not null
//active bool,
//communications_complete_date timestamp,
//complete_date timestamp,
//country_of_origin uuid references common.locations(id),
//disbursement_complete_date timestamp,
//end_date timestamp,
//end_date_override timestamp,
//growth_plan uuid references common.files(id), --references files, not file-versions in neo4j
//initial_end_date timestamp,
//intern uuid references admin.people(id),
//last_reactivated_at timestamp,
//mentor uuid references admin.people(id),
//methodologies common.product_methodologies[],
//paratext_registry varchar(32),
//periodic_reports_directory uuid references sc.periodic_reports_directory(id),
//position common.internship_position,
//sensitivity common.sensitivity,
//start_date timestamp,
//start_date_override timestamp,
//status common.engagement_status,
//status_modified_at timestamp,
//last_suspended_at timestamp,


data class internshipEngagementInput(
    var id: String? = null,

    val project: String? = null,
    val change_to_plan: String? = null,
    val active: Boolean? = null,
    val ceremony: String? = null,
    val communications_complete_date: String? = null,
    val complete_date: String? = null,
    val country_of_origin: String? = null,
    val disbursement_complete_date: String? = null,
    val end_date: String? = null,
    val end_date_override: String? = null,
    val growth_plan: String? = null,
    val initial_end_date: String? = null,
    val intern: String? = null,
    val last_reactivated_at: String? = null,
    val mentor: String? = null,
    val methodologies: String? = null,
    val paratext_registry: String? = null,
    val periodic_reports_directory: String? = null,
    val position: String? = null,
    val sensitivity: String? = null,
    val start_date: String? = null,
    val start_date_override: String? = null,
    val status: String? = null,
    val status_modified_at: String? = null,
    val last_suspended_at: String? = null,

    val created_at: String? = null,
    val created_by: String? = null,
    val modified_at: String? = null,
    val modified_by: String? = null,
    val owning_person: String? = null,
    val owning_group: String? = null,
)

