/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, RouterHistory } from "@stencil/router";
import { ActionType } from "./common/types";
import { MenuClickedEvent } from "./components/header/types";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
        "history": RouterHistory;
    }
    interface CfAction {
        "actionFn": (value: any) => Promise<boolean>;
        "actionType": ActionType;
        "text": any;
        "value": any;
    }
    interface CfCell {
        "isEditable": boolean;
        "options"?: Array<string>;
        "propKey": keyof any;
        "rowId": number;
        "type"?: string;
        "updateFn": (id: number, columnName: any, value: any) => Promise<boolean>;
        "value": any;
    }
    interface CfHeader {
        "history": RouterHistory;
    }
    interface CfHeaderMenu {
        "history": RouterHistory;
    }
    interface CfLogin {
        "history": RouterHistory;
    }
    interface CfRegister {
        "history": RouterHistory;
    }
    interface CommonOrganizations {
    }
    interface CreateUpdateModal {
        "isOpen": boolean;
        "modalTitle": String;
    }
    interface GenericTable {
        "columns": Array<any>;
        "name": String;
        "values": Array<any>;
    }
    interface GlobalRoleColumnGrants {
        "history": RouterHistory;
    }
    interface GlobalRoleMemberships {
    }
    interface GlobalRoleTablePermissions {
    }
    interface GlobalRoles {
    }
    interface GroupMemberships {
    }
    interface GroupsRowAccess {
    }
    interface GroupsTable {
    }
    interface LanguagesEx {
    }
    interface ScriptureReferences {
    }
    interface TableRoot {
        "match": MatchResults;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCfActionElement extends Components.CfAction, HTMLStencilElement {
    }
    var HTMLCfActionElement: {
        prototype: HTMLCfActionElement;
        new (): HTMLCfActionElement;
    };
    interface HTMLCfCellElement extends Components.CfCell, HTMLStencilElement {
    }
    var HTMLCfCellElement: {
        prototype: HTMLCfCellElement;
        new (): HTMLCfCellElement;
    };
    interface HTMLCfHeaderElement extends Components.CfHeader, HTMLStencilElement {
    }
    var HTMLCfHeaderElement: {
        prototype: HTMLCfHeaderElement;
        new (): HTMLCfHeaderElement;
    };
    interface HTMLCfHeaderMenuElement extends Components.CfHeaderMenu, HTMLStencilElement {
    }
    var HTMLCfHeaderMenuElement: {
        prototype: HTMLCfHeaderMenuElement;
        new (): HTMLCfHeaderMenuElement;
    };
    interface HTMLCfLoginElement extends Components.CfLogin, HTMLStencilElement {
    }
    var HTMLCfLoginElement: {
        prototype: HTMLCfLoginElement;
        new (): HTMLCfLoginElement;
    };
    interface HTMLCfRegisterElement extends Components.CfRegister, HTMLStencilElement {
    }
    var HTMLCfRegisterElement: {
        prototype: HTMLCfRegisterElement;
        new (): HTMLCfRegisterElement;
    };
    interface HTMLCommonOrganizationsElement extends Components.CommonOrganizations, HTMLStencilElement {
    }
    var HTMLCommonOrganizationsElement: {
        prototype: HTMLCommonOrganizationsElement;
        new (): HTMLCommonOrganizationsElement;
    };
    interface HTMLCreateUpdateModalElement extends Components.CreateUpdateModal, HTMLStencilElement {
    }
    var HTMLCreateUpdateModalElement: {
        prototype: HTMLCreateUpdateModalElement;
        new (): HTMLCreateUpdateModalElement;
    };
    interface HTMLGenericTableElement extends Components.GenericTable, HTMLStencilElement {
    }
    var HTMLGenericTableElement: {
        prototype: HTMLGenericTableElement;
        new (): HTMLGenericTableElement;
    };
    interface HTMLGlobalRoleColumnGrantsElement extends Components.GlobalRoleColumnGrants, HTMLStencilElement {
    }
    var HTMLGlobalRoleColumnGrantsElement: {
        prototype: HTMLGlobalRoleColumnGrantsElement;
        new (): HTMLGlobalRoleColumnGrantsElement;
    };
    interface HTMLGlobalRoleMembershipsElement extends Components.GlobalRoleMemberships, HTMLStencilElement {
    }
    var HTMLGlobalRoleMembershipsElement: {
        prototype: HTMLGlobalRoleMembershipsElement;
        new (): HTMLGlobalRoleMembershipsElement;
    };
    interface HTMLGlobalRoleTablePermissionsElement extends Components.GlobalRoleTablePermissions, HTMLStencilElement {
    }
    var HTMLGlobalRoleTablePermissionsElement: {
        prototype: HTMLGlobalRoleTablePermissionsElement;
        new (): HTMLGlobalRoleTablePermissionsElement;
    };
    interface HTMLGlobalRolesElement extends Components.GlobalRoles, HTMLStencilElement {
    }
    var HTMLGlobalRolesElement: {
        prototype: HTMLGlobalRolesElement;
        new (): HTMLGlobalRolesElement;
    };
    interface HTMLGroupMembershipsElement extends Components.GroupMemberships, HTMLStencilElement {
    }
    var HTMLGroupMembershipsElement: {
        prototype: HTMLGroupMembershipsElement;
        new (): HTMLGroupMembershipsElement;
    };
    interface HTMLGroupsRowAccessElement extends Components.GroupsRowAccess, HTMLStencilElement {
    }
    var HTMLGroupsRowAccessElement: {
        prototype: HTMLGroupsRowAccessElement;
        new (): HTMLGroupsRowAccessElement;
    };
    interface HTMLGroupsTableElement extends Components.GroupsTable, HTMLStencilElement {
    }
    var HTMLGroupsTableElement: {
        prototype: HTMLGroupsTableElement;
        new (): HTMLGroupsTableElement;
    };
    interface HTMLLanguagesExElement extends Components.LanguagesEx, HTMLStencilElement {
    }
    var HTMLLanguagesExElement: {
        prototype: HTMLLanguagesExElement;
        new (): HTMLLanguagesExElement;
    };
    interface HTMLScriptureReferencesElement extends Components.ScriptureReferences, HTMLStencilElement {
    }
    var HTMLScriptureReferencesElement: {
        prototype: HTMLScriptureReferencesElement;
        new (): HTMLScriptureReferencesElement;
    };
    interface HTMLTableRootElement extends Components.TableRoot, HTMLStencilElement {
    }
    var HTMLTableRootElement: {
        prototype: HTMLTableRootElement;
        new (): HTMLTableRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "cf-action": HTMLCfActionElement;
        "cf-cell": HTMLCfCellElement;
        "cf-header": HTMLCfHeaderElement;
        "cf-header-menu": HTMLCfHeaderMenuElement;
        "cf-login": HTMLCfLoginElement;
        "cf-register": HTMLCfRegisterElement;
        "common-organizations": HTMLCommonOrganizationsElement;
        "create-update-modal": HTMLCreateUpdateModalElement;
        "generic-table": HTMLGenericTableElement;
        "global-role-column-grants": HTMLGlobalRoleColumnGrantsElement;
        "global-role-memberships": HTMLGlobalRoleMembershipsElement;
        "global-role-table-permissions": HTMLGlobalRoleTablePermissionsElement;
        "global-roles": HTMLGlobalRolesElement;
        "group-memberships": HTMLGroupMembershipsElement;
        "groups-row-access": HTMLGroupsRowAccessElement;
        "groups-table": HTMLGroupsTableElement;
        "languages-ex": HTMLLanguagesExElement;
        "scripture-references": HTMLScriptureReferencesElement;
        "table-root": HTMLTableRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
        "history"?: RouterHistory;
    }
    interface CfAction {
        "actionFn"?: (value: any) => Promise<boolean>;
        "actionType"?: ActionType;
        "text"?: any;
        "value"?: any;
    }
    interface CfCell {
        "isEditable"?: boolean;
        "options"?: Array<string>;
        "propKey"?: keyof any;
        "rowId"?: number;
        "type"?: string;
        "updateFn"?: (id: number, columnName: any, value: any) => Promise<boolean>;
        "value"?: any;
    }
    interface CfHeader {
        "history"?: RouterHistory;
    }
    interface CfHeaderMenu {
        "history"?: RouterHistory;
        "onMenuClicked"?: (event: CustomEvent<MenuClickedEvent>) => void;
    }
    interface CfLogin {
        "history"?: RouterHistory;
    }
    interface CfRegister {
        "history"?: RouterHistory;
    }
    interface CommonOrganizations {
    }
    interface CreateUpdateModal {
        "isOpen"?: boolean;
        "modalTitle"?: String;
        "onModalClosed"?: (event: CustomEvent<boolean>) => void;
        "onModalDelete"?: (event: CustomEvent<boolean>) => void;
        "onModalOkay"?: (event: CustomEvent<boolean>) => void;
    }
    interface GenericTable {
        "columns"?: Array<any>;
        "name"?: String;
        "onRowClicked"?: (event: CustomEvent<number>) => void;
        "values"?: Array<any>;
    }
    interface GlobalRoleColumnGrants {
        "history"?: RouterHistory;
    }
    interface GlobalRoleMemberships {
    }
    interface GlobalRoleTablePermissions {
    }
    interface GlobalRoles {
    }
    interface GroupMemberships {
    }
    interface GroupsRowAccess {
    }
    interface GroupsTable {
    }
    interface LanguagesEx {
    }
    interface ScriptureReferences {
    }
    interface TableRoot {
        "match"?: MatchResults;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "cf-action": CfAction;
        "cf-cell": CfCell;
        "cf-header": CfHeader;
        "cf-header-menu": CfHeaderMenu;
        "cf-login": CfLogin;
        "cf-register": CfRegister;
        "common-organizations": CommonOrganizations;
        "create-update-modal": CreateUpdateModal;
        "generic-table": GenericTable;
        "global-role-column-grants": GlobalRoleColumnGrants;
        "global-role-memberships": GlobalRoleMemberships;
        "global-role-table-permissions": GlobalRoleTablePermissions;
        "global-roles": GlobalRoles;
        "group-memberships": GroupMemberships;
        "groups-row-access": GroupsRowAccess;
        "groups-table": GroupsTable;
        "languages-ex": LanguagesEx;
        "scripture-references": ScriptureReferences;
        "table-root": TableRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "cf-action": LocalJSX.CfAction & JSXBase.HTMLAttributes<HTMLCfActionElement>;
            "cf-cell": LocalJSX.CfCell & JSXBase.HTMLAttributes<HTMLCfCellElement>;
            "cf-header": LocalJSX.CfHeader & JSXBase.HTMLAttributes<HTMLCfHeaderElement>;
            "cf-header-menu": LocalJSX.CfHeaderMenu & JSXBase.HTMLAttributes<HTMLCfHeaderMenuElement>;
            "cf-login": LocalJSX.CfLogin & JSXBase.HTMLAttributes<HTMLCfLoginElement>;
            "cf-register": LocalJSX.CfRegister & JSXBase.HTMLAttributes<HTMLCfRegisterElement>;
            "common-organizations": LocalJSX.CommonOrganizations & JSXBase.HTMLAttributes<HTMLCommonOrganizationsElement>;
            "create-update-modal": LocalJSX.CreateUpdateModal & JSXBase.HTMLAttributes<HTMLCreateUpdateModalElement>;
            "generic-table": LocalJSX.GenericTable & JSXBase.HTMLAttributes<HTMLGenericTableElement>;
            "global-role-column-grants": LocalJSX.GlobalRoleColumnGrants & JSXBase.HTMLAttributes<HTMLGlobalRoleColumnGrantsElement>;
            "global-role-memberships": LocalJSX.GlobalRoleMemberships & JSXBase.HTMLAttributes<HTMLGlobalRoleMembershipsElement>;
            "global-role-table-permissions": LocalJSX.GlobalRoleTablePermissions & JSXBase.HTMLAttributes<HTMLGlobalRoleTablePermissionsElement>;
            "global-roles": LocalJSX.GlobalRoles & JSXBase.HTMLAttributes<HTMLGlobalRolesElement>;
            "group-memberships": LocalJSX.GroupMemberships & JSXBase.HTMLAttributes<HTMLGroupMembershipsElement>;
            "groups-row-access": LocalJSX.GroupsRowAccess & JSXBase.HTMLAttributes<HTMLGroupsRowAccessElement>;
            "groups-table": LocalJSX.GroupsTable & JSXBase.HTMLAttributes<HTMLGroupsTableElement>;
            "languages-ex": LocalJSX.LanguagesEx & JSXBase.HTMLAttributes<HTMLLanguagesExElement>;
            "scripture-references": LocalJSX.ScriptureReferences & JSXBase.HTMLAttributes<HTMLScriptureReferencesElement>;
            "table-root": LocalJSX.TableRoot & JSXBase.HTMLAttributes<HTMLTableRootElement>;
        }
    }
}
