cord:
  admin:
    password: ${CORD_ADMIN_PASSWORD}
  init:
    load-db-version: ${LOAD_DB_VERSION}
spring:
  mvc:
    async:
      request-timeout: -1
  datasource:
    url: jdbc:postgresql://${DB_DOMAIN}:5432/ct2
    jdbcUrl: jdbc:postgresql://${DB_DOMAIN}:5432/ct2
    driverClassName: software.aws.rds.jdbc.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    ssl: ${DB_SSL}
  hikari:
    connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
    minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
    maximum-pool-size: 10 #maximum pool size
    idle-timeout: 10000 #maximum idle time for connection
    max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
    auto-commit: true #default auto-commit behavior.