package com.seedcompany.cordtables.components.tables.sc.language_ex

data class LanguageEx(
    var id: Int? = null,
    val name: String? = null,
    val prioritization: Double? = null,
    val progress_bible: Boolean? = null,
    val location_long: String? = null,
    val island: String? = null,
    val province: String? = null,
    val first_language_population: Int? = null,
    val population_value: Double? = null,
    val egids_level: EgidsScale? = null,
    val egids_value: Double? = null,
    val least_reached_progress_jps_level: LeastReachedProgressScale? = null,
    val least_reached_value: Double? = null,
    val partner_interest_level: PartnerInterestScale? = null,
    val partner_interest_value: Double? = null,
    val partner_interest_description: String? = null,
    val partner_interest_source: String? = null,
    val multiple_languages_leverage_linguistic_level: MultipleLanguagesLeverageLinguisticScale? = null,
    val multiple_languages_leverage_linguistic_value: Double? = null,
    val multiple_languages_leverage_linguistic_description: String? = null,
    val multiple_languages_leverage_linguistic_source: String? = null,
    val multiple_languages_leverage_joint_training_level: MultipleLanguagesLeverageJointTrainingScale? = null,
    val multiple_languages_leverage_joint_training_value: Double? = null,
    val multiple_languages_leverage_joint_training_description: String? = null,
    val multiple_languages_leverage_joint_training_source: String? = null,
    val lang_comm_int_in_language_development_level: LangCommIntInLanguageDevelopmentScale? = null,
    val lang_comm_int_in_language_development_value: Double? = null,
    val lang_comm_int_in_language_development_description: String? = null,
    val lang_comm_int_in_language_development_source: String? = null,
    val lang_comm_int_in_scripture_translation_level: LangCommIntInScriptureTranslationScale? = null,
    val lang_comm_int_in_scripture_translation_value: Double? = null,
    val lang_comm_int_in_scripture_translation_description: String? = null,
    val lang_comm_int_in_scripture_translation_source: String? = null,
    val access_to_scripture_in_lwc_level: AccessToScriptureInLwcScale? = null,
    val access_to_scripture_in_lwc_value: Double? = null,
    val access_to_scripture_in_lwc_description: String? = null,
    val access_to_scripture_in_lwc_source: String? = null,
    val begin_work_geo_challenges_level: BeginWorkGeoChallengesScale? = null,
    val begin_work_geo_challenges_value: Double? = null,
    val begin_work_geo_challenges_description: String? = null,
    val begin_work_geo_challenges_source: String? = null,
    val begin_work_rel_pol_obstacles_level: BeginWorkRelPolObstaclesScale? = null,
    val begin_work_rel_pol_obstacles_value: Double? = null,
    val begin_work_rel_pol_obstacles_description: String? = null,
    val begin_work_rel_pol_obstacles_source: String? = null,
    val suggested_strategies: String? = null,
    val comments: String? = null,
    val created_at: String? = null,
    val created_by: Int? = null,
    val modified_at: String? = null,
    val modified_by: Int? = null,
    val owning_person: Int? = null,
    val owning_group: Int? = null,
    val peer: Int? = null,
)

data class LanguageExInput(
    var id: Int? = null,
    val name: String? = null,
    val prioritization: Double? = null,
    val progress_bible: Boolean? = null,
    val location_long: String? = null,
    val island: String? = null,
    val province: String? = null,
    val first_language_population: Int? = null,
    val population_value: Double? = null,
    val egids_level: String? = null,
    val egids_value: Double? = null,
    val least_reached_progress_jps_level: String? = null,
    val least_reached_value: Double? = null,
    val partner_interest_level: String? = null,
    val partner_interest_value: Double? = null,
    val partner_interest_description: String? = null,
    val partner_interest_source: String? = null,
    val multiple_languages_leverage_linguistic_level: String? = null,
    val multiple_languages_leverage_linguistic_value: Double? = null,
    val multiple_languages_leverage_linguistic_description: String? = null,
    val multiple_languages_leverage_linguistic_source: String? = null,
    val multiple_languages_leverage_joint_training_level: String? = null,
    val multiple_languages_leverage_joint_training_value: Double? = null,
    val multiple_languages_leverage_joint_training_description: String? = null,
    val multiple_languages_leverage_joint_training_source: String? = null,
    val lang_comm_int_in_language_development_level: String? = null,
    val lang_comm_int_in_language_development_value: Double? = null,
    val lang_comm_int_in_language_development_description: String? = null,
    val lang_comm_int_in_language_development_source: String? = null,
    val lang_comm_int_in_scripture_translation_level: String? = null,
    val lang_comm_int_in_scripture_translation_value: Double? = null,
    val lang_comm_int_in_scripture_translation_description: String? = null,
    val lang_comm_int_in_scripture_translation_source: String? = null,
    val access_to_scripture_in_lwc_level: String? = null,
    val access_to_scripture_in_lwc_value: Double? = null,
    val access_to_scripture_in_lwc_description: String? = null,
    val access_to_scripture_in_lwc_source: String? = null,
    val begin_work_geo_challenges_level: String? = null,
    val begin_work_geo_challenges_value: Double? = null,
    val begin_work_geo_challenges_description: String? = null,
    val begin_work_geo_challenges_source: String? = null,
    val begin_work_rel_pol_obstacles_level: String? = null,
    val begin_work_rel_pol_obstacles_value: Double? = null,
    val begin_work_rel_pol_obstacles_description: String? = null,
    val begin_work_rel_pol_obstacles_source: String? = null,
    val suggested_strategies: String? = null,
    val comments: String? = null,
    val created_at: String? = null,
    val created_by: Int? = null,
    val modified_at: String? = null,
    val modified_by: Int? = null,
    val owning_person: Int? = null,
    val owning_group: Int? = null,
    val peer: Int? = null,
)

enum class EgidsScale(val value: Float)  {
    `0`(1.0F),
    `1`(1.0F),
    `2`(1.0F),
    `3`(1.0F),
    `4`(0.9F),
    `5`(0.8F),
    `6a`(0.6F),
    `6b`(0.4F),
    `7`(0.3F),
    `8a`(0.2F),
    `8b`(0.1F),
    `9`(0.0F),
    `10`(0.0F),
}

enum class LeastReachedProgressScale(val value: Float)  {
    `1`(1.00F),
    `2`(0.75F),
    `3`(0.50F),
    `4`(0.25F),
    `5`(0.00F),
}

enum class PartnerInterestScale(val value: Float)  {
    NoPartnerInterest(0.00F),
    Some(0.33F),
    Significant(0.66F),
    Considerable(1.00F),
}

enum class MultipleLanguagesLeverageLinguisticScale(val value: Float)  {
    None(0.0F),
    Some(0.2F),
    Significant(0.4F),
    Considerable(0.6F),
    Large(0.8F),
    Vast(1.0F),
}

enum class MultipleLanguagesLeverageJointTrainingScale(val value: Float)  {
    None(0.0F),
    Some(0.2F),
    Significant(0.4F),
    Considerable(0.6F),
    Large(0.8F),
    Vast(1.0F),
}

enum class LangCommIntInLanguageDevelopmentScale(val value: Float) {
    NoInterest(0.00F),
    Some(0.33F),
    Significant(0.67F),
    Considerable(1.00F),
}

enum class LangCommIntInScriptureTranslationScale(val value: Float)  {
    NoInterest(0.00F),
    Some(0.25F),
    ExpressedNeed(0.50F),
    Significant(0.75F),
    Considerable(1.00F),
}

enum class AccessToScriptureInLwcScale(val value: Float)  {
    FullAccess(0.00F),
    VastMajority(0.16F),
    LargeMajority(0.33F),
    Majority(0.50F),
    Significant(0.66F),
    Some(0.83F),
    Few(1.00F),
}

enum class BeginWorkGeoChallengesScale(val value: Float) {
    None(-0.50F),
    VeryDifficult(0.00F),
    Difficult(0.33F),
    Moderate(0.66F),
    Easy(1.00F),
}

enum class BeginWorkRelPolObstaclesScale(val value: Float)  {
    None(0.00F),
    VeryDifficult(0.25F),
    Difficult(0.50F),
    Moderate(0.75F),
    Easy(1.00F),
}
