alter table sc.posts and unique (neo4j_id);
alter table sc.funding_accounts alter column account_number set unique not null;
alter table sc.funding_accounts and unique (neo4j_id);
alter table sc.field_zones alter column name set not null;
alter table sc.field_regions alter column name set not null;
alter table sc.locations alter column name set unique not null;
alter table sc.locations alter column type set not null;
alter table sc.locations and unique (neo4j_id);
alter table sc.organizations and unique (neo4j_id);
alter table sc.partners and unique (neo4j_id);
alter table sc.partners alter column organization set not null;
alter table sc.ethnologue and unique (neo4j_id);
alter table sc.languages and unique (neo4j_id);
alter table sc.languages alter column ethnologue set not null;
alter table sc.languages alter column name set unique not null;
alter table sc.languages alter column display_name set unique not null;
alter table sc.people and unique (neo4j_id);
alter table sc.periodic_reports alter column directory set not null;
alter table sc.periodic_reports alter column end_at set not null;
alter table sc.periodic_reports alter column report_file set not null;
alter table sc.periodic_reports alter column start_at set not null;
alter table sc.periodic_reports alter column type set not null;
alter table sc.projects alter column name set not null;
alter table sc.projects alter column change_to_plan set not null;
alter table sc.project_members and unique (project, person, group_id, role);
alter table sc.project_members alter column project set not null;
alter table sc.project_members alter column person set not null;
alter table sc.project_members alter column group_id set not null;
alter table sc.project_members alter column role set not null;
alter table sc.pinned_projects alter column person set not null;
alter table sc.pinned_projects alter column project set not null;
alter table sc.partnerships alter column project set not null;
alter table sc.partnerships alter column partner set not null;
alter table sc.partnerships alter column change_to_plan set not null;
alter table sc.partnerships and unique (neo4j_id);
alter table sc.partnerships_producing_mediums alter column medium set not null;
alter table sc.partnerships_producing_mediums alter column partnership set not null;
alter table sc.budgets alter column change_to_plan set not null;
alter table sc.budgets alter column project set not null;
alter table sc.budgets and unique (neo4j_id);
alter table sc.budget_records alter column budget set not null;
alter table sc.budget_records alter column change_to_plan set not null;
alter table sc.project_locations alter column change_to_plan set not null;
alter table sc.project_locations alter column location set not null;
alter table sc.project_locations alter column project set not null;
alter table sc.language_engagements alter column project set not null;
alter table sc.language_engagements alter column languages set not null;
alter table sc.language_engagements alter column change_to_plan set not null;
alter table sc.language_locations alter column language set not null
alter table sc.language_locations alter column location set not null
alter table sc.products alter column name set not null;
alter table sc.products alter column change_to_plan set not null;
alter table sc.product_scripture_references alter column product set not null;
alter table sc.product_scripture_references alter column scripture_reference set not null;
alter table sc.product_scripture_references alter column change_to_plan set not null;
alter table sc.internship_engagements alter column project set not null;
alter table sc.internship_engagements alter column change_to_plan set not null;
alter table admin.users alter column email set not null;
